package service

import (
  "crypto/tls"
  "fmt"

  gomail "gopkg.in/mail.v2"
)

func SendEmail(sender, receiver, subject, body string) error{
	m := gomail.NewMessage()

	// Set E-Mail sender
	//m.SetHeader("From", "sharmahitesh472001@gmail.com")
	m.SetHeader("From", sender)

	// Set E-Mail receivers
	//m.SetHeader("To", "hitesh@mail.busy.in")
	m.SetHeader("To", receiver)

	// Set E-Mail subject
	//m.SetHeader("Subject", "Gomail test subject")
	m.SetHeader("Subject", subject)

	// Set E-Mail body. You can set plain text or html with text/html
	// m.SetBody("text/plain", "This is Gomail test body")

	m.SetBody("text/plain", body)

	// Settings for SMTP server
	//SMTP server requires an app password to allow authorization, it is autogenerated and can be created by heading to google account settings
	d := gomail.NewDialer("smtp.gmail.com", 587, sender, "nwpe jpuu uynm lqjk")

	// This is only needed when SSL/TLS certificate is not valid on server.
	// In production this should be set to false.
	d.TLSConfig = &tls.Config{InsecureSkipVerify: true}

	// Now send E-Mail
	if err := d.DialAndSend(m); err != nil {
		fmt.Println(err)
		return err
	}

	fmt.Println("Email succesfully sent ")
	return nil
}